### PR TITLE
Namespace reorg

### PR DESCRIPTION
**Pull request by ericnewton76**
Namespace reorg as proposed by #22

1. Moved all System.Diagnostics to (root) namespace.  
2. Moved any supporting types into ObjectDumperLib
3. Keep Tests working!

### CODE REVIEW

**Comment by ericnewton76** [comment]
I gotta say, as I was making changes, I appreciate how well built this project is.

Tests were thorough, well organized as well.  

Whats funny is i'm amazed you were able to compile without "using System;" in many of these files... System.Func<>, System.IDisposable, etc came up as missing.

**Comment by ericnewton76** [comment]
Ok I merged your changes in.  

Just note, overall I moved the ObjectDumper type into the global namespace.  

You could actually prepend `this` to the Dump method and it becomes an extension method that attaches to all System.Object (basically everything).

Or, make somebody "decide" to have that by making them add `using ObjectDumperLib` or `ObjectDumperExtensions` to get the extension methods.

What do you think about either?  I'm leaning towards the latter.

**Comment by ericnewton76** [comment]
Another thought: because we're in the global namespace, it might be wise to rename DumpStyle and DumpOptions to ObjectDumperStyle and ObjectDumperOptions to significantly reduce any clashing.

I mention this just for completeness.

**Comment by thomasgalliker** [comment]
Hmm.. what about moving all code to ObjectDumping namespace? I used to practice this naming convention in former projects: Namespace "Tracing" contains "Tracer", namespace "ObjectDumping" contains "ObjectDumper", etc..

**Comment by ericnewton76** [comment]
Sounds reasonable.

Should we keep the Extension Methods in a separate namespace or `ObjectDumping` ?   Makes sense for them to be in `ObjectDumping`

**Comment by ericnewton76** [comment]
Btw, to keep the ObjectDumping namespace even tighter, I moved the ObjectDumperCSharp and ObjectDumperConsole into ObjectDumping.Internal   Both those types could probably then transition to public instead of internal, if you want.

The way it is now is pretty much a good fit... very tight.  ;)

**Comment by thomasgalliker** [comment]
Also, the internal *Extensions.cs I would rather move to a Folder „Internal“ than „Extensions“. I think „Extensions“ is better reserved for public extension methods. I gonna have a look at it soon again.

**Comment by ericnewton76** [comment]
I was actually thinking the same thing.  Will incorporate those into Internal namespace.

Btw, the force push is from removing a commit that added an .editorconfig file

**Comment by ericnewton76** [comment]
Allright good sir! Check it out.  See what you think.  I'm out for the night... lol

**Comment by thomasgalliker** [comment]
Could you test the pre-release nuget? I gonna do this today. Afterwards, I‘ll close this thread.

**Pull request merged**
