### PR TITLE
Handle DateTimeOffset formatting

### PR DESCRIPTION
**Pull request by corinblaikie**
Currently the CSharp dumber dumps DateTimeOffset values like this:

```
var dateTimeOffset = new DateTimeOffset`
{
  DateTime = DateTime.ParseExact("2000-01-01T23:59:59.0000000", "O", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
  UtcDateTime = DateTime.ParseExact("2000-01-01T23:59:59.0000000Z", "O", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
  LocalDateTime = DateTime.ParseExact("2000-01-02T12:59:59.0000000+13:00", "O", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
  Date = DateTime.ParseExact("2000-01-01T00:00:00.0000000", "O", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
  Day = 1,
  DayOfWeek = System.DayOfWeek.Saturday,
  DayOfYear = 1,
  Hour = 23,
  Millisecond = 0,
  Minute = 59,
  Month = 1,
  Offset = new TimeSpan
  {
    Ticks = 0L,
    Days = 0,
    Hours = 0,
    Milliseconds = 0,
    Minutes = 0,
    Seconds = 0,
    TotalDays = 0d,
    TotalHours = 0d,
    TotalMilliseconds = 0d,
    TotalMinutes = 0d,
    TotalSeconds = 0d
  },
  Second = 59,
  Ticks = 630823679990000000L,
  UtcTicks = 630823679990000000L,
  TimeOfDay = new TimeSpan
  {
    Ticks = 863990000000L,
    Days = 0,
    Hours = 23,
    Milliseconds = 0,
    Minutes = 59,
    Seconds = 59,
    TotalDays = 0.999988425925926d,
    TotalHours = 23.9997222222222d,
    TotalMilliseconds = 86399000d,
    TotalMinutes = 1439.98333333333d,
    TotalSeconds = 86399d
  },
  Year = 2000
};
```

instead of something small like:
```
DateTimeOffset.ParseExact("2000-01-01T23:59:59.0000000+00:00", "O", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind);
```

### CODE REVIEW

**Comment by thomasgalliker** [comment]
Wow, ok, I was obvisouly only tackling the DateTime type... sorry for that.

**Comment by corinblaikie** [comment]
@thomasgalliker no problem, thanks for creating this project!

**Comment by thomasgalliker** [comment]
There should be a nuget pre-release dropping out soon. Version 2.4.19323.06-pre (and newer) will contain your change. Can you download it (as soon as it is available on nuget.org) and let me know if everything is fine? I'll trigger a master (stable) build then. Thanks for your effert, again!

**Pull request merged**
