### PR TITLE
Add member renamer

### PR DESCRIPTION
**Pull request by lofcz**
In some cases it is needed to return properties renamed. For example many embedded languages libs expose clr members under different name by default (Scriban, Moonsharp..). This PR adds a simple function we can pipe property name through and modify it before it is commited. This is nonbreaking change.

### CODE REVIEW

**Comment by lofcz** [comment]
@thomasgalliker 

> "Good products are copied often". However, it confuses nuget users if you copy code on github and re-publish it under a different name on [nuget.org](http://nuget.org/). I can only speak for ObjectDumper.NET: I kindly ask you to remove the cloned ObjectDumper.NET-lof from [nuget.org](http://nuget.org/). Use your own packages internally or setup your own private nuget server. If you want to contribute to existing packages (which is highly welcome), stick to the official contibution process of the respective github repository. Ok? :)

Hi Thomas,
first off, thanks for reaching out. I've opened this PR on Mar 9 and since I got no response from you, I've opened my own fork with the proposed (minor) change and published the package so me and my friends could use it with this improvement, which is critical for us. It was never an intention to impersonate your package and I've made no such changes to the source code. All links from my fork are linking back to you and it is clearly labeled as a personal fork. 
It saddens me that you view an action of forking your repository and publishing a publicly available nuget of said fork (again, with changes) as stealing/impersonating.
I'll of course honor your request and I've unlisted `ObjectDumper.NET-lof` package immediatly after getting your e-mail (5 hrs ago). There were 52 downloads on it to date.

image


If I may, I have two questions to ask:
- Have you considered merging #92 or is there something blocking it?
- Could you please add `LICENSE.md` file? Now there is a license block in the main readme but it is unclear (at least for me) under which license is this library available. You state that you are the copyright owner (implicit unless stated otherwise) and that the library can be used for non commercial projects for free (my case). If a standard license (bsd, mit, gpl...) fitting your criteria could be found and possibly used in LICENSE.md file it would be clearer to see whether your library can or can't be used in projects interested.

For this reason I've dropped `ObjectDumper.NET` from my project until licensing is resolved.

I'm replying in an open letter for the sake of transparency under the original PR I've opened as per: 

> stick to the official contibution process of the respective github repository. Ok? :)

this part of your e-mail.

Thanks and please accept my apology for the inconvenience I've caused you.

**Comment by thomasgalliker** [comment]
@lofcz I merged your pull request, finally. Please have a look at https://www.nuget.org/packages/ObjectDumper.NET/3.3.22-pre and let me know if everything is as expected.

**Pull request merged**
